### PR TITLE
code churn

### PR DESCRIPTION
**Pull request by jetersen**
Some general csproj cleanup using the new project format and package references.
Added some more editorconfig rules to cleanup various whitespaces left around.
made Logger.cs a static class and removed the instance method.

I considered applying the redundant code cleanup but I will follow up in a separate PR 😅

### CODE REVIEW

**Comment by casz** [comment]
Assert.Equal is not very helpful here...
Switching to FluentAsserts :)

**Comment by casz** [comment]
Also the tests and build assumes tskill is accessible, I would feel safer using the more verbose taskkill.

**Comment by casz** [comment]
Seems like I found a bug.

That I can reproduce locally, if I run the tests it runs CmdTests and than PowerShellTests the problem is that gsudo is now affected by CmdTests and behaves differently with line ending it seems.

If I only run PowerShellTests the tests passes.

If I change the order.

I tried going back and forth, this happens after I changed the csproj (now sure how that affects the runtime)

Seems like previously the tests were not failing, even though some of them should have.
If you have look at https://github.com/gerardog/gsudo/pull/12/commits/2424e49201787b7de3618544b1b2d6a7945ff3c8

**Comment by casz** [comment]
This is the bug:

PS_EchoNoQuotesTest output
```
# ./gsudo 'echo 1 2 3'
1# exit

```

PS_EchoNoQuotesTest expected
```
# ./gsudo 'echo 1 2 3'
1
2
3
# exit

```

**Comment by casz** [comment]
Bug is related to parent host being detected as `C:\Users\josep\scoop\apps\dotnet-sdk\current\sdk\3.1.101\TestHost\testhost.x86.exe` instead of powershell

**Comment by gerardog** [comment]
Thanks for the contribution. I am on a busy vacation time right now so, when i got some time I will fix the tests before merging into master.

**Comment by casz** [comment]
No worries @gerardog have a great vacation! 👏 

Thanks for taking the time and letting me know.

One issue I can see with the current tests is the attached debugger cannot see into the execution.
Wonder if it was possible to launch the process with the debugger attaching itself, so you cold step through and find the bug.

**Pull request closed without merging**
