### PR TITLE
docs: improve README.md manual installation technique, fixes #296

### LINKED ISSUE #296: README: Manually: Unzip the latest release, and add to the path.
## Issue Description

I've been using a fork for DDEV's install for some time but really want to use your releases. It's by far easiest to use a exe file, as requested in https://github.com/gerardog/gsudo/issues/88, but I'm moving on!

It seems like the README may be from long ago. it says:

> Manually: Unzip the latest release, and add to the path

I assume this means "Unzip gsudo_portable.zip" and extract the gsudo.exe from it. But there are lots of things in there:

```
$ unzip -l gsudo.portable.zip
Archive:  gsudo.portable.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
      717  07-17-2023 23:23   x86/gsudo
 16965760  07-17-2023 23:24   x86/gsudo.exe
    20323  07-17-2023 23:24   x86/gsudoModule.psd1
    26037  07-17-2023 23:24   x86/gsudoModule.psm1
    22814  07-17-2023 23:24   x86/Invoke-gsudo.ps1
      717  07-17-2023 23:23   x64/gsudo
  5871568  07-17-2023 23:24   x64/gsudo.exe
    20323  07-17-2023 23:24   x64/gsudoModule.psd1
    26037  07-17-2023 23:24   x64/gsudoModule.psm1
    22814  07-17-2023 23:24   x64/Invoke-gsudo.ps1
      717  07-17-2023 23:23   arm64/gsudo
  6063056  07-17-2023 23:24   arm64/gsudo.exe
    20323  07-17-2023 23:24   arm64/gsudoModule.psd1
    26037  07-17-2023 23:24   arm64/gsudoModule.psm1
    22814  07-17-2023 23:24   arm64/Invoke-gsudo.ps1
      717  07-17-2023 23:23   net46-AnyCpu/gsudo
   192464  07-17-2023 23:24   net46-AnyCpu/gsudo.exe
      174  07-17-2023 23:23   net46-AnyCpu/gsudo.exe.config
    20323  07-17-2023 23:24   net46-AnyCpu/gsudoModule.psd1
    26037  07-17-2023 23:24   net46-AnyCpu/gsudoModule.psm1
    22814  07-17-2023 23:24   net46-AnyCpu/Invoke-gsudo.ps1
```

I would bet that I would want the x64/gsudo.exe for any ordinary Windows machine. Is that the only thing I need?

### PR DESCRIPTION
**Pull request by rfay**
* #296

Just adds some more detail to the manual install technique.

### CODE REVIEW

**Comment by gerardog** [comment]
Thank you rfay!

**Comment by rfay** [comment]
Thanks for this great tool.

**Comment by rfay** [comment]
BTW, I think we'll end up doing two installers, one aimed at choco, which does not include gsudo; the other will include gsudo bundled and will be the one we offer for "normal" download. Then there won't be a download at install time.

**Comment by gerardog** [comment]
Are you sure you want to go thru so much trouble?

- Arguments for embedding it:
   - It is unlikely that gsudo will be flagged as a virus in the future if you follow these rules. There is a 30-day window since a new gsudo build is uploaded until it gets popular enough (gaining reputation on AV scanners). The first day generally gets a score of 1/60 or 2/60... which drops to 0/60 after a few weeks. The mistake made by chocolatey by considering 1/60 low score as dangerous was already fixed and should not affect your software packaging, in my opinion.
   - You may include a well-known gsudo.exe in your distribution, and if you update it, you can always pick one that is already has a low score.
- Arguments against embedding it:
    - gsudo does not handles gracefully having more than one binary in use, as the credentials cache rejects connections from another .EXE files.
    - gsudo experience is not the same on WSL/bash without the wrappers... (I would install not just `gsudo.EXE`)

But putting myself in your situation... I would:
   - Trigger the independent installation of gsudo, a) as a post install task or b) during DDev first run 
   - In DDev: before invoking gsudo, handling what happens if gsudo is not installed: 
       - a) just trigger the installer. Your app just need to call this line `PowerShell -Command "Set-ExecutionPolicy RemoteSigned -scope Process; [Net.ServicePointManager]::SecurityProtocol = 'Tls12'; iwr -useb https://raw.githubusercontent.com/gerardog/gsudo/master/installgsudo.ps1 | iex"`
       - b) you can always just start an elevated process with 'verb=runas' as a fallback for those outliers rejecting to install gsudo...

**Comment by rfay** [comment]
Thanks for the good thinking, I sure appreciate it. 

> You may include a well-known gsudo.exe in your distribution, and if you update it, you can always pick one that is already has a low score.

So just explicitly use an old one with a good virustotal score? How would I figure that out?

**Comment by rfay** [comment]
Linking to the DDEV PR to show what actually ended up happening and so we can find these various (great) discussions:
* https://github.com/ddev/ddev/pull/5314

**Pull request merged**
