### PR TITLE
fix call to bash wrapper `gsudo` without PATH env var set

### PR DESCRIPTION
**Pull request by lsiu**
## Problem
In WSL, when gsudo is not in `PATH` env var, the bash wrapper script cannot run because `gsudo.exe` is called without a path.

## Solution
Assuming the `gsudo` bash script will always be in the same directory as `gsudo.exe`, we can use `$( dirname -- "$0" )`. See https://stackoverflow.com/a/59916/84091

### CODE REVIEW

**Review by gerardog — APPROVED** [review]

**Comment by lsiu** [comment]
@gerardog , it looks like it is stuck at "Test Expected - Wiating for status to be report". Is there something I need to do?

**Comment by alanlivio** [comment]
thanks @lsiu and @gerardog.
I just update to  v2.0.7 (from v2.0.6) and received the fallowing error from wsl.

```
> wsl
$ whereis gsudo
gsudo: /mnt/c/Program Files/gsudo/2.0.7/gsudo
$ gsudo
/mnt/c/Program Files/gsudo/Current/gsudo: line 11: /mnt/c/Program: No such file or directory
```

See more info:

```
> wsl --version
WSL version: 1.2.5.0
Kernel version: 5.15.90.1
WSLg version: 1.0.51
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22624.1470
```

```
> gsudo -v
gsudo v2.0.7 (Branch.tags-v2.0.7.Sha.0cdab2c7a833ee65bac017142abbc0339bceafa9)
Copyright(c) 2019-2022 Gerardo Grignoli and GitHub contributors
```

**Comment by gerardog** [comment]
Hi @alanlivio.
What WSL distro are you using?

**Comment by gerardog** [comment]
Hi again @alanlivio, thx for reporting. This was fixed in #259 and released in v2.0.8

**Comment by alanlivio** [comment]
Many thanks @gerardog. I tried the v2.0.8 and the "No such file ..." error was fixed.

Also, about my WSL distro.

```
> wsl -l
Windows Subsystem for Linux Distributions:
Ubuntu (Default)
> wsl
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
```

But I was expecting that this new version would fix error #239 below but I still have it:

```
$ gsudo --version
gsudo v2.0.8 (Branch.tags-v2.0.8.Sha.e01151333ddd4e76b2e0808545835dd56a16c905)
Copyright(c) 2019-2022 Gerardo Grignoli and GitHub contributors

$ gsudo pwd
'\\wsl.localhost\Ubuntu\home\alan'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
/mnt/c/Windows
```

**Pull request merged**
