### PR TITLE
Fixed null check on the original variable to use String.IsNullOrEmpty…

### PR DESCRIPTION
**Pull request by trparky**
…() instead of a simple == null check.

### CODE REVIEW

**Comment by gerardog** [comment]
@trparky What specific problem are you trying to fix?
A string replace function shall not return null when the input is an empty string. 
Do you happen to think that String.IsNullOrEmpty() is superior than `==null`?

**Comment by trparky** [comment]
I guess it's a style issue that bugs me. When I see one line of code that uses one method and another line of code that uses a different method, it sort of bugs me.

**Comment by gerardog** [comment]
But there is a reason for not using string.isnullorempty there.

**Comment by trparky** [comment]
OK then, I'll close out this merge request as not accepted.

**Pull request closed without merging**
