### PR TITLE
add -NoProfile argument to PowerShell Core as default

### LINKED ISSUE #10: PowerShell Core 7.0.0-rc2 loads with profile.
When launching gsudo from powershell core v7.0.0-rc2 it launches with profile.

See my profile here: https://github.com/casz/dotfiles/blob/master/powershell/profile.ps1

image

Of course I could remove my "Modules Loaded" message 🤔 But it seems that it also adds two new lines in pwsh rather than just one newline.

### PR DESCRIPTION
**Pull request by casz**
fixes #10

### CODE REVIEW

**Comment by gerardog** [comment]
Thanks @casz.
The PR fixes PowerShell Core 7.x, but is not working for me under 6.x. (Truth be told, the issue with 6.x was happening before this PR).

What I am seeing is that neither `-Command` nor `-NoProfile` are accepted as valid arguments.
It throws:
`-NoProfile : The term '-NoProfile' is not recognized as the name of a cmdlet, function, script file, or operable program.`

According to PowerShell/PowerShell#10355 this may be caused by the way I installed pwsh 6.x, which was to run:  `dotnet tool install powershell --global` plus (`--version 6.2.3`)

This means that for 6.x installed as a global tool, PowerShellCore6Arguments should be ""
The profile will be loaded, but at least some functionality remains.

If you install using the [MSI/ZIP installer](https://github.com/PowerShell/PowerShell/releases/download/v6.2.3/PowerShell-6.2.3-win-x64.msi), then arguments are properly parsed and PowerShellCore6Arguments can be `-NoProfile -Command`. It works without loading the profile.

Options:
* Use `PowerShellCore6Arguments='-NoProfile -Command'` and make it work as expected only if installed via `MSI`
* Use `PowerShellCore6Arguments=''` -Command` and load the profile but at least it runs on both instalation types.
* Figure out how to detect if running as a dotnet global tool and have different settings case by case...

**Comment by casz** [comment]
Should be easy enough to detect .dotnet\tools in the path of pwsh.exe 🤔

**Comment by casz** [comment]
If the tool is installed by `dotnet tool --global` the path looks like this:

```powershell
# exe is located in .dotnet\tools
"C:\Users\josep\.dotnet\tools\pwsh.exe"
# in that folder there is a .store 
"C:\Users\josep\.dotnet\tools\.store"
# with the each tool installed
"C:\Users\josep\.dotnet\tools\.store\powershell\6.2.3"
```

The location can change with `DOTNET_CLI_HOME` however `.dotnet\tools` will always be the case.

**Comment by gerardog** [comment]
I few weeks back I read the discussions in the PowerShell repo, and somewhere (I cant find the exact link now) they agreed it would be a breaking change for 6.x so they decided to fix it only into 7.x, so [they did](https://github.com/PowerShell/PowerShell/issues/10301#issuecomment-533239364).

**Comment by casz** [comment]
As it was approved for 6.2.4 I think we are fine:
https://github.com/PowerShell/PowerShell/pull/10461#event-2959890147

**Pull request merged**
